.include "m328pdef.inc"
.include "delay.inc"

; Arduino AVR Code.asm
;
; Created: 14/12/2023 11:20:22 pm
; Author : Wali

.cseg
.org 0x00
					;INPUT CONFIGURATION
	CBI DDRD, PD2 ; PB5 SET AS INPUT PIN FOR YELLOW LIGHT
	SBI PORTD, PD2 ; Enable internal pull-up resistor

	CBI DDRD, PD3 ; PB4 SET AS INPUT PIN FOR MAGENTA LIGHT
	SBI PORTD, PD3 ; Enable internal pull-up resistor

	CBI DDRD, PD4 ; PD7 SET AS INPUT PIN FOR WHITE LIGHT
	SBI PORTD, PD4 ; Enable internal pull-up resistor

	CBI DDRD, PD5 ; PD6 SET AS INPUT PIN FOR ON AND OFF ALL LIGHTS IN LOOP
	SBI PORTD, PD5 ; Enable internal pull-up resistor

	CBI DDRD, PD6 ; PD6 SET AS INPUT PIN FOR OFF ALL LIGHTS
	SBI PORTD, PD6 ; Enable internal pull-up resistor

					;OUTPUT CONFIGURATION
	SBI DDRB, PB1 ; PB1 set as OUTPUT Pin RED LIGHT
	CBI PORTB, PB1 ; LED OFF

	SBI DDRB, PB2 ; PB2 set as OUTPUT Pin GREEN LIGHT
	CBI PORTB, PB2 ; LED OFF

	SBI DDRB, PB3 ; PB3 set as OUTPUT Pin BLUE LIGHT
	CBI PORTB, PB3 ; LED OFF
	
	SBI DDRB, PB4 ; PB3 set as OUTPUT Pin for BUZZER
	
	SBI PORTB, PB4 ; TURN BUZZER ON
	delay 1500
	delay 1500
	CBI PORTB, PB4 ; TURN BUZZER OFF
	
	SBI PORTB, PB1	;RED LED ON
	SBI PORTB, PB2	;GREEN LED ON
	SBI PORTB, PB3	;BLUE LED ON
	delay 2000
	CBI PORTB, PB1	;RED LED ON
	CBI PORTB, PB2	;GREEN LED ON
	CBI PORTB, PB3	;BLUE LED ON

MAIN:
	SBIS PIND, PD6
	rjmp LEDS_OFF
		
	SBIS PIND, PD5
	rjmp LOOP_LEDS
	
	SBIS PIND, PD4
	rjmp WHITE_LED
	
	SBIS PIND, PD3
	rjmp MAGENTA_LED
	
	SBIS PIND, PD2
	rjmp YELLOW_LED
rjmp MAIN

LEDS_OFF:
	CBI PORTB, PB1	;RED LED OFF
	CBI PORTB, PB2	;GREEN LED OFF
	CBI PORTB, PB3	;BLUE LED OFF
rjmp MAIN

RED_LED:
	SBI PORTB, PB1	;RED LED ON
	CBI PORTB, PB2	;GREEN LED OFF
	CBI PORTB, PB3	;BLUE LED OFF
rjmp MAIN

GREEN_LED:
	CBI PORTB, PB1	;RED LED OFF
	SBI PORTB, PB2	;GREEN LED ON
	CBI PORTB, PB3	;BLUE LED OFF
rjmp MAIN

BLUE_LED:
	CBI PORTB, PB1	;RED LED OFF
	CBI PORTB, PB2	;GREEN LED OFF
	SBI PORTB, PB3	;BLUE LED ON
rjmp MAIN

YELLOW_LED:
	SBI PORTB, PB1	;RED LED ON
	SBI PORTB, PB2	;GREEN LED ON
	CBI PORTB, PB3	;BLUE LED OFF
rjmp MAIN

MAGENTA_LED:
	SBI PORTB, PB1	;RED LED ON
	CBI PORTB, PB2	;GREEN LED OFF
	SBI PORTB, PB3	;BLUE LED ON
rjmp MAIN

CYAN_LED:
	CBI PORTB, PB1	;RED LED OFF
	SBI PORTB, PB2	;GREEN LED ON
	SBI PORTB, PB3	;BLUE LED ON
rjmp MAIN

WHITE_LED:
	SBI PORTB, PB1	;RED LED ON
	SBI PORTB, PB2	;GREEN LED ON
	SBI PORTB, PB3	;BLUE LED ON
rjmp MAIN

LOOP_LEDS:
	SBI PORTB, PB1	;RED LED ON
	CBI PORTB, PB2	;GREEN LED OFF
	CBI PORTB, PB3	;BLUE LED OFF
	
	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	CBI PORTB, PB1	;RED LED OFF
	SBI PORTB, PB2	;GREEN LED ON
	CBI PORTB, PB3	;BLUE LED OFF

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	CBI PORTB, PB1	;RED LED OFF
	CBI PORTB, PB2	;GREEN LED OFF
	SBI PORTB, PB3	;BLUE LED ON

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	SBI PORTB, PB1	;RED LED ON
	SBI PORTB, PB2	;GREEN LED ON
	CBI PORTB, PB3	;BLUE LED OFF

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	SBI PORTB, PB1	;RED LED ON
	CBI PORTB, PB2	;GREEN LED OFF
	SBI PORTB, PB3	;BLUE LED ON

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	SBI PORTB, PB1	;RED LED ON
	CBI PORTB, PB2	;GREEN LED OFF
	SBI PORTB, PB3	;BLUE LED ON

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	SBI PORTB, PB1	;RED LED ON
	SBI PORTB, PB2	;GREEN LED ON
	SBI PORTB, PB3	;BLUE LED ON

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	CBI PORTB, PB1	;RED LED OFF
	CBI PORTB, PB2	;GREEN LED OFF
	CBI PORTB, PB3	;BLUE LED OFF

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN

	delay 500

	SBIS PIND, PD6
	rjmp MAIN
	SBIS PIND, PD5
	rjmp MAIN
	SBIS PIND, PD4
	rjmp MAIN
	SBIS PIND, PD3
	rjmp MAIN
	SBIS PIND, PD2
	rjmp MAIN
	 
rjmp LOOP_LEDS